# ─────────────────────────────────────────────────────────────────────────────
# _config.yml (minimal for Just the Docs)
# ─────────────────────────────────────────────────────────────────────────────

plugins:
  - jekyll-remote-theme

remote_theme: pmarsceill/just-the-docs

title: "Coolgogi’s Blog"
description: "Programming, Book/Movie/Game Reviews, and more"
url: "https://coolgogi.github.io"
baseurl: ""   # leave empty for a user site

locale: "ko-KR"

just_the_docs:
  version: "latest"
  search_enabled: true
  sidebar_menu: true
  toc_enabled: true
  toc_levels: 1..6
  include_default_header: true
  include_default_footer: true

collections:
# ─────────── Add these lines to declare a “notes” collection ───────────
  notes:
    output: true
    permalink: /notes/:title/   # so each note’s page lives at /notes/slug/
# ─────────── Add these lines to declare a “books” collection ───────────
  books:
    output: true
    permalink: /books/:title/   # so each book’s page lives at /books/slug/
# ─────────── Add these lines to declare a "movies” collection ───────────
  movies:
    output: true
    permalink: /movies/:title/   # so each movie’s page lives at /movies/slug/
# ─────────── Add these lines to declare a “games” collection ───────────
  games:
    output: true
    permalink: /games/:title/   # so each game’s page lives at /games/slug/
# ───────────────────────────────────────────────────────────────────────────
